name: Run Crunchbase Ingestion

on:
  push:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run ingestion script
      env:
        CRUNCHBASE_API_KEY: ${{ secrets.CRUNCHBASE_API_KEY }}
      run: |
        python ingest_crunchbase.py
